
all:
   cd procq
   nmake 
   cd ..
   cd modq
   nmake 
   cd ..
   cd handleq
   nmake 
   cd ..
   cd winq
   nmake 
   cd ..
   cd netq
   nmake 
   cd ..

clean:
   cd procq
   nmake clean
   cd ..
   cd modq
   nmake clean
   cd ..
   cd handleq
   nmake clean
   cd ..
   cd winq
   nmake clean
   cd ..
   cd netq
   nmake clean
   cd ..
